### ISSUE TITLE
Parâmetro -p sem funcionamento

### ISSUE THREAD

**Issue by GustavoJatene** [S4TURN0/atomic-python#2]
O parâmetro -p não está funcionando.

![image](https://user-images.githubusercontent.com/15218606/120503729-ed163400-c399-11eb-9e14-df69a6ad47b2.png)

Para o portscan voltar a funcionar com somente portas específicas eu comentei a condição (if args.portscan == True:), abaixo está o teste, porém cria outro problema com o parâmetro -f, na call de hoje podemos ver essas questões. 

![image](https://user-images.githubusercontent.com/15218606/120504230-58600600-c39a-11eb-833a-2de6f766ac0e.png)

**Comment by S4TURN0** [comment]
Problema resolvido com sucesso!
